name: environment workflow

run-name: environment workflow

on:
 push:
  branches: main
 pull_request:
  branches: main
 workflow_dispatch:
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: compile
     run: echo hello,world
     
 
 
